#ifndef MEMMAP_H_
#define MEMMAP_H_

#define GB_JOYP_ADDR                        (0xFF00)
#define GB_SB_ADDR                          (0xFF01)
#define GB_SC_ADDR                          (0xFF02)
#define GB_DIV_ADDR                         (0xFF04)
#define GB_TIMA_ADDR                        (0xFF05)
#define GB_TMA_ADDR                         (0xFF06)
#define GB_TAC_ADDR                         (0xFF07)
#define GB_IF_ADDR                          (0xFF0F)
#define GB_IE_ADDR                          (0xFFFF)
#define GB_NR52_ADDR                        (0xFF26)
#define GB_NR51_ADDR                        (0xFF25)
#define GB_NR50_ADDR                        (0xFF24)
#define GB_NR10_ADDR                        (0xFF10)
#define GB_NR11_ADDR                        (0xFF11)
#define GB_NR12_ADDR                        (0xFF12)
#define GB_NR13_ADDR                        (0xFF13)
#define GB_NR14_ADDR                        (0xFF14)
#define GB_NR21_ADDR                        (0xFF16)
#define GB_NR22_ADDR                        (0xFF17)
#define GB_NR23_ADDR                        (0xFF18)
#define GB_NR24_ADDR                        (0xFF19)
#define GB_NR30_ADDR                        (0xFF1A)
#define GB_NR31_ADDR                        (0xFF1B)
#define GB_NR32_ADDR                        (0xFF1C)
#define GB_NR33_ADDR                        (0xFF1D)
#define GB_NR34_ADDR                        (0xFF1E)
#define GB_WAVE_PATTERN_RAM_START_ADDR      (0xFF30)
#define GB_WAVE_PATTERN_RAM_END_ADDR        (0xFF3F)
#define GB_NR41_ADDR                        (0xFF20)
#define GB_NR42_ADDR                        (0xFF21)
#define GB_NR43_ADDR                        (0xFF22)
#define GB_NR44_ADDR                        (0xFF23)
#define GB_LCDC_ADDR                        (0xFF40)
#define GB_LY_ADDR                          (0xFF44)
#define GB_LYC_ADDR                         (0xFF45)
#define GB_STAT_ADDR                        (0xFF41)
#define GB_SCY_ADDR                         (0xFF42)
#define GB_SCX_ADDR                         (0xFF43)
#define GB_WY_ADDR                          (0xFF4A)
#define GB_WX_ADDR                          (0xFF4B)
#define GB_BGP_ADDR                         (0xFF47)
#define GB_OBP0_ADDR                        (0xFF48)
#define GB_OBP1_ADDR                        (0xFF49)
#define GB_BOOT_ROM_DISABLED_ADDR           (0xFF50)

#define GB_JOYP                             (gb->memory[GB_JOYP_ADDR]                   & 0xFF)
#define GB_SB                               (gb->memory[GB_SB_ADDR]                     & 0xFF)
#define GB_SC                               (gb->memory[GB_SC_ADDR]                     & 0xFF)
#define GB_DIV                              (gb->memory[GB_DIV_ADDR]                    & 0xFF)
#define GB_TIMA                             (gb->memory[GB_TIMA_ADDR]                   & 0xFF)
#define GB_TMA                              (gb->memory[GB_TMA_ADDR]                    & 0xFF)
#define GB_TAC                              (gb->memory[GB_TAC_ADDR]                    & 0xFF)
#define GB_IF                               (gb->memory[GB_IF_ADDR]                     & 0x1F)
#define GB_IE                               (gb->memory[GB_IE_ADDR]                     & 0x1F)
#define GB_NR52                             (gb->memory[GB_NR52_ADDR]                   & 0xFF)
#define GB_NR51                             (gb->memory[GB_NR51_ADDR]                   & 0xFF)
#define GB_NR50                             (gb->memory[GB_NR50_ADDR]                   & 0xFF)
#define GB_NR10                             (gb->memory[GB_NR10_ADDR]                   & 0xFF)
#define GB_NR11                             (gb->memory[GB_NR11_ADDR]                   & 0xFF)
#define GB_NR13                             (gb->memory[GB_NR13_ADDR]                   & 0xFF)
#define GB_NR14                             (gb->memory[GB_NR14_ADDR]                   & 0xFF)
#define GB_NR21                             (gb->memory[GB_NR21_ADDR]                   & 0xFF)
#define GB_NR22                             (gb->memory[GB_NR22_ADDR]                   & 0xFF)
#define GB_NR23                             (gb->memory[GB_NR23_ADDR]                   & 0xFF)
#define GB_NR24                             (gb->memory[GB_NR24_ADDR]                   & 0xFF)
#define GB_NR30                             (gb->memory[GB_NR30_ADDR]                   & 0xFF)
#define GB_NR31                             (gb->memory[GB_NR31_ADDR]                   & 0xFF)
#define GB_NR32                             (gb->memory[GB_NR32_ADDR]                   & 0xFF)
#define GB_NR33                             (gb->memory[GB_NR33_ADDR]                   & 0xFF)
#define GB_NR34                             (gb->memory[GB_NR34_ADDR]                   & 0xFF)
#define GB_WAVE_PATTERN_START               (gb->memory[GB_WAVE_PATTERN_RAM_START_ADDR] & 0xFF)
#define GB_WAVE_PATTERN_END                 (gb->memory[GB_WAVE_PATTERN_RAM_END_ADDR]   & 0xFF)
#define GB_NR41                             (gb->memory[GB_NR41_ADDR]                   & 0xFF)
#define GB_NR42                             (gb->memory[GB_NR42_ADDR]                   & 0xFF)
#define GB_NR43                             (gb->memory[GB_NR43_ADDR]                   & 0xFF)
#define GB_NR44                             (gb->memory[GB_NR44_ADDR]                   & 0xFF)
#define GB_LCDC                             (gb->memory[GB_LCDC_ADDR]                   & 0xFF)
#define GB_LY                               (gb->memory[GB_LY_ADDR]                     & 0xFF)
#define GB_LYC                              (gb->memory[GB_LYC_ADDR]                    & 0xFF)
#define GB_STAT                             (gb->memory[GB_STAT_ADDR]                   & 0xFF)
#define GB_SCY                              (gb->memory[GB_SCY_ADDR]                    & 0xFF)
#define GB_SCX                              (gb->memory[GB_SCX_ADDR]                    & 0xFF)
#define GB_WY                               (gb->memory[GB_WY_ADDR]                     & 0xFF)
#define GB_WX                               (gb->memory[GB_WX_ADDR]                     & 0xFF)

#endif